import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Xのようなスマホアプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {children}


        <div className="text-center mt-4">
            <p>
              <a href="https://jasonwatmore.com/next-js-13-app-router-mongodb-user-rego-and-login-tutorial-with-example" target="_blank">Next.js 13 + App Router + MongoDB - User Rego and Login Tutorial with Example</a>
            </p>
            <p>
              <a href="https://jasonwatmore.com" target="_blank">JasonWatmore.com</a>
            </p>
        </div>
      </body>
    </html>
  );
}
