'use client';

import { ReactNode } from 'react';
import { RecoilRoot } from 'recoil';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Xのようなスマホアプリ",
//   description: "Generated by create next app",
// };

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <RecoilRoot>
      <html lang="en">
        <body>{children}</body>
      </html>
    </RecoilRoot>
  );
};

export default RootLayout;
