import Image from "next/image";

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h1 className="text-3xl font-bold">Xのようなスマホアプリ</h1>
      <p className="text-xl">Generated by create next app</p>
      <Image
        src="/logo.svg"
        alt="logo"
        width={200}
        height={200}
      />
    </main>
  );
}
